"""empty message

Revision ID: 2a414ae43066
Revises: 2d84efd395bf
Create Date: 2024-04-23 10:25:28.625765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a414ae43066'
down_revision = '2d84efd395bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_username_key', ['username'])

    # ### end Alembic commands ###
