"""empty message

Revision ID: 454423c8b5f1
Revises: 2a414ae43066
Create Date: 2024-04-23 10:28:03.767476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454423c8b5f1'
down_revision = '2a414ae43066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=25), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
