"""changed token

Revision ID: 8329710ecd4b
Revises: bb44108138ac
Create Date: 2024-04-23 16:54:16.778708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8329710ecd4b'
down_revision = 'bb44108138ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
