"""removed username

Revision ID: bb44108138ac
Revises: 454423c8b5f1
Create Date: 2024-04-23 16:39:17.058431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb44108138ac'
down_revision = '454423c8b5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')
        batch_op.drop_column('pw_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pw_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_username_key', ['username'])

    # ### end Alembic commands ###
