"""working on imade ID issues

Revision ID: ebc83d7a3f35
Revises: 71c9e6274f31
Create Date: 2024-04-24 09:10:32.496160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc83d7a3f35'
down_revision = '71c9e6274f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.drop_column('uploaded_by_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('client_user_id')

    # ### end Alembic commands ###
