"""empty message

Revision ID: f359d3465d9c
Revises: 
Create Date: 2024-04-26 11:53:44.550822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f359d3465d9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dog_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dog', ['dog_id'], ['dog_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dog_id')

    # ### end Alembic commands ###
